.\" Man page for the program format, hw7 of CSCI 241
.\" Shiying Zheng and Ben Stern - Fall 2013

.TH FORMAT 1 "09 November 2013" "CSCI 241" "Oberlin College"

.SH NAME
.B sort
\- sort lines of text from standard input

.SH SYNOPSIS
.B sort
[ -f ] [ -r ] [ -n ] [ -h ] [ -? ] 

.SH DESCRIPTION
.B format
sorts the lines of text from standard input. Default is sort by ASCII value, lowest value first.

.SH OPTIONS
.IP "-f case folding / case insensitive"
.IP "-r reverse sort"
.IP "-n sort by numbers at the beginning of the line"

.SH AUTHOR
Shiying Zheng(Fall 2013)
Benjamin Stern(Fall 2013)

.SH BUGS
None!
